### ISSUE TITLE
[Ursine Polar] it's hard to identify text from background when rename file

### ISSUE THREAD

**Issue by TiaossuP** [aCluelessDanny/typora-theme-ursine#18]
Typora Version: Typora 0.9.9.25.3(2879)

In Ursine Polar 1.6.2, I found a small issue when I try to rename my file.

![image](https://user-images.githubusercontent.com/9267217/60780864-b403c380-a172-11e9-9a89-874aa06d0a5f.png)

In casually, it's easy to solve by some CSS like this:

```css
#file-library-tree div.file-node-content > div.file-tree-rename-div > input.file-tree-rename-input {
  color: #808080;
}
```

Nevertheless, this post is still just a issue report. A official solution is still yearned to help more users.

Thank you so much for your contribution. (･ェ･。)
