### ISSUE TITLE
inline code blocks look nothing like multiline code blocks 

### ISSUE THREAD

**Issue by skewty** [aCluelessDanny/typora-theme-ursine#52]
The software development team I work on uses markdown to document our projects.
I really like your Ursine Umbra theme except for one detail.
The inline code blocks look nothing like multiline code blocks.
Code should stand out and look like code, whether it is inline or multiline in my opinion.

Suggested fix:
```css
code {
  font-size: .9em;
  border: 1px solid #ffffff26;
  border-radius: .25rem;
  padding: 0.25rem .5rem;
  background-color: #282a36;
}

```
I additionally wanted this to give a bit more space between normal text and code blocks since the padding was increased but it isn't working.  I tried Sh-F12 to use the Dev Tools to diagnose but 
Typora kept locking up on me so I gave up.

```css
code:not(:first-child) {
  margin-left: 0.25rem;
}
code:not(:last-child) {
    margin-right: 0.25rem;
}
```

Your thoughts?
